from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.homepage,  name='homepage'),
    path("panel", views.panel,  name='panel'),
    path("nuevo_trabajador", views.nuevo_trabajador, name="nuevo_trabajador"),
    path("trabajadores", views.trabajadores,  name='trabajadores'),
    path("trabajadores/<trabajador>", views.trabajador, name="trabajador"),
    path("trabajadores/<trabajador>/actualizar", views.trabajador_update, name="actualizar_trabajador"),
    path("trabajadores/<trabajador>/eliminar", views.trabajador_delete, name="eliminar_trabajador"),
    path("nuevo_paquete", views.nuevo_paquete, name="nuevo_paquete"),
    path("paquetes", views.paquetes,  name='paquetes'),
    path("paquetes/<paquete>", views.paquete, name="paquete"),
    path("paquetes/<paquete>/actualizar", views.paquete_update, name="actualizar_paquete"),
    path("paquetes/<paquete>/eliminar", views.paquete_delete, name="eliminar_paquete"),
    path("nuevo_contrato", views.nuevo_contrato, name="nuevo_contrato"),
    path("contratos", views.contratos,  name='contratos'),
    path("contratos/<contrato>", views.contrato , name="contrato"),
    path("contratos/<contrato>/actualizar", views.contrato_update, name="actualizar_contrato"),
    path("contratos/<contrato>/eliminar", views.contrato_delete, name="eliminar_contrato"),
    path("nuevo_templo", views.nuevo_templo, name="nuevo_templo"),
    path("templos", views.templos,  name='templos'),
    path("templos/<templo>", views.templo , name="templo"),
    path("templos/<templo>/actualizar", views.templo_update, name="actualizar_templo"),
    path("templos/<templo>/eliminar", views.templo_delete, name="eliminar_templo"),
    path("nuevo_ubicacion", views.nuevo_ubicacion, name="nuevo_ubicacion"),
    path("ubicaciones", views.ubicaciones,  name='ubicaciones'),
    path("ubicaciones/<ubicacion>", views.ubicacion , name="ubicacion"),
    path("ubicaciones/<ubicacion>/actualizar", views.ubicacion_update, name="actualizar_ubicacion"),
    path("ubicaciones/<ubicacion>/eliminar", views.ubicacion_delete, name="eliminar_ubicacion"),
    path("nuevo_salon", views.nuevo_salon, name="nuevo_salon"),
    path("salones", views.salones,  name='salones'),
    path("salones/<salon>", views.salon , name="salon"),
    path("salones/<salon>/actualizar", views.salon_update, name="actualizar_salon"),
    path("salones/<salon>/eliminar", views.salon_delete, name="eliminar_salon"),
    path("nuevo_asignacion", views.nuevo_asignacion, name="nuevo_asignacion"),
    path("asignaciones", views.asignaciones,  name='asignaciones'),
    path("asignaciones/<asignacion>", views.asignacion , name="asignacion"),
    path("asignaciones/<asignacion>/actualizar", views.asignacion_update, name="actualizar_asignacion"),
    path("asignaciones/<asignacion>/eliminar", views.asignacion_delete, name="eliminar_asignacion"),
    path("nuevo_venta", views.nuevo_venta, name="nuevo_venta"),
    path("ventas", views.ventas,  name='ventas'),
    path("ventas/<venta>", views.venta , name="templo"),
    path("ventas/<venta>/actualizar", views.venta_update, name="actualizar_venta"),
    path("ventas/<venta>/eliminar", views.venta_delete, name="eliminar_venta"),
]
