# Generated by Django 4.2.4 on 2023-08-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('codigo_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paquete', models.CharField(max_length=30)),
                ('descripcion_paquete', models.CharField(max_length=255)),
                ('precio_paquete', models.PositiveSmallIntegerField(default=5)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('codigo_salon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_salon', models.CharField(max_length=30)),
                ('ubicacion_salon', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='Templo',
            fields=[
                ('codigo_templo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_templo', models.CharField(max_length=30)),
                ('ubicacion_templo', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('codigo_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=30)),
                ('tipo_trabajo', models.CharField(choices=[('Foto', 'Fotógrafo'), ('Vídeo', 'Vídeo'), ('Foto y Vídeo', 'Foto y Vídeo'), ('Mostrador', 'Mostrador')], default='F', max_length=100)),
                ('empleado_activo', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codigo_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=30)),
                ('tipo_ubicacion', models.CharField(choices=[('A', 'Acámbaro'), ('R', 'Rancho')], default='R', max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('folio_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.PositiveSmallIntegerField(default=5)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('paquete_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paquete')),
                ('usuario_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('folio_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente_contrato', models.CharField(max_length=100)),
                ('fecha_contrato', models.DateField()),
                ('tipo_evento_contrato', models.CharField(max_length=50)),
                ('hora_contrato', models.CharField(max_length=10)),
                ('nota_contrato', models.TextField()),
                ('contrato_activo', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('lugar_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ubicacion')),
                ('paquete_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paquete')),
                ('salon_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salon')),
                ('templo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.templo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_asignacion', models.CharField(choices=[('Fotos', 'Fotógrafo'), ('Vídeo', 'Vídeo'), ('Sesión', 'Sesión')], default='F', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contrato_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contrato')),
                ('empleado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trabajador')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
