# Generated by Django 4.2.4 on 2023-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='tipo_trabajo',
            field=models.CharField(choices=[('Foto', 'Fotógrafo'), ('Vídeo', 'Vídeo'), ('Foto y Vídeo', 'Foto y Vídeo'), ('Mostrador', 'Mostrador')], default='Foto', max_length=100),
        ),
    ]
